/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:63cee57b-225c-40f9-b1a3-d9e61e53eca7",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_QyBzq2X6h",
    "aws_user_pools_web_client_id": "2ukbeebospb2q7ems4djurh0a1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "http://192.168.56.1:20002/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


export default awsmobile;
